/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package the.guardian.api.client;

import com.mashape.unirest.http.exceptions.UnirestException;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import the.guardian.api.http.AbstractResponse;

import java.io.UnsupportedEncodingException;

public class GuardianApiTest {
    private GuardianApi guardianApi;

    @BeforeEach
    public void setUp() {
        this.guardianApi = new GuardianApi("9cb97729-b42b-4c0a-832a-84cc03c43841");
    }

    @Test
    public void testGetContent() throws UnsupportedEncodingException, UnirestException {
       AbstractResponse contentResponse = this.guardianApi.content().setQuery("12 years a slave").setTag("film/film,tone/reviews").setFromDate("2023-03-20").setShowTags("contributor").setShowFields("starRating,headline,thumbnail,short-url").setOrderBy("relevance").fetch();
        System.out.println(contentResponse);
    }

    @Test
    public void testGetTags() throws UnsupportedEncodingException, UnirestException {
        AbstractResponse tagsResponse = this.guardianApi.tags().setQuery("apple").setSection("technology").setShowReferences("all").fetch();
        System.out.println(tagsResponse);
    }

    @Test
    public void testGetSections() throws UnsupportedEncodingException, UnirestException {
        AbstractResponse sectionsResponse = this.guardianApi.sections().setQuery("business").fetch();
        System.out.println(sectionsResponse);
    }

    @Test
    public void testGetEditions() throws UnsupportedEncodingException, UnirestException {
        AbstractResponse editionsResponse = this.guardianApi.editions().setQuery("uk").fetch();
        System.out.println(editionsResponse);
    }

    @Test
    public void testGetSingleItem() throws UnsupportedEncodingException, UnirestException {
        AbstractResponse singleItemResponse = this.guardianApi.singleItem().setId("/sport/2022/oct/07/cricket-jos-buttler-primed-for-england-comeback-while-phil-salt-stays-focused").setShowStoryPackage(true).setShowEditorsPicks(true).setShowMostViewed(true).setShowRelated(true).fetch();
        System.out.println(singleItemResponse);
    }
}
